import * as fs from 'fs';
import * as path from 'path';
import { ParsedComponent, DSKitConfig } from './types.js';

export function generateMCPConfig(
  components: ParsedComponent[],
  storybookUrl: string,
  outputDir: string
): void {
  const config: DSKitConfig = {
    name: 'design-system',
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    storybookUrl,
    totalComponents: components.length,
    components: components.map((c) => ({
      ...c,
      propCount: c.props.length,
      variantCount: c.variants.length,
    })),
  };

  const outputPath = path.join(outputDir, 'mcp-config.json');
  fs.writeFileSync(outputPath, JSON.stringify(config, null, 2), 'utf-8');
}

export function generateMarkdown(
  components: ParsedComponent[],
  storybookUrl: string,
  outputDir: string
): void {
  const lines: string[] = [
    '# Design System Components',
    `Generated by DSKit from ${storybookUrl}`,
    `Generated at: ${new Date().toISOString()}`,
    `Total components: ${components.length}`,
    '',
    '> Drop this file into your project root.',
    '> Cursor and Claude Code will automatically use it to suggest components.',
    '',
    '---',
    '',
  ];

  for (const component of components) {
    lines.push(`## ${component.name}`);

    if (component.description) {
      lines.push(`**Description:** ${component.description}`);
    }

    lines.push(`**Category:** ${component.category}`);

    if (component.props.length > 0) {
      lines.push('**Props:**');
      for (const prop of component.props) {
        const optionsStr = prop.options ? ` (${prop.options.map((o) => `"${o}"`).join(' | ')})` : '';
        const defaultStr = prop.default !== undefined ? ` — default: "${prop.default}"` : '';
        const requiredStr = prop.required ? ' *(required)*' : '';
        lines.push(`  - **${prop.name}**${requiredStr}: ${prop.type}${optionsStr}${defaultStr}`);
        if (prop.description) {
          lines.push(`    ${prop.description}`);
        }
      }
    } else {
      lines.push('**Props:** Not documented (add JSDoc comments to your component)');
    }

    if (component.variants.length > 0) {
      lines.push(`**Variants:** ${component.variants.join(', ')}`);
    }

    lines.push(`**Storybook:** ${component.docsUrl}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  const outputPath = path.join(outputDir, 'COMPONENTS.md');
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
}
