import * as fs from 'fs';
import * as path from 'path';
import { ParsedComponent } from './types.js';
import { GLOBAL_RULES, findAppearanceProp, findStateProps, buildForbiddenBullets } from './rules.js';

export function generateRules(
  components: ParsedComponent[],
  storybookUrl: string,
  outputDir: string
): void {
  const lines: string[] = [
    '# Design System Rules & Usage Patterns',
    `Generated by DSKit from ${storybookUrl}`,
    `Generated at: ${new Date().toISOString()}`,
    '',
    '> **For Cursor and Claude Code:** Read before generating any component usage.',
    '> Never violate FORBIDDEN patterns. Always use props for appearance, not className.',
    '',
    '---',
    '',
    '## Core Principle',
    '',
    'Every component has a sealed visual contract:',
    '- Appearance = explicit props (variant, size, color, tone, state)',
    '- className = layout ONLY (margin, position, flex, grid)',
    '- Never className for colors, padding, typography, borders',
    '- Never inline style for visual overrides',
    '',
    '---',
    '',
    '## Global Rules (apply to ALL components)',
    '',
    '### Safe className (layout only):',
    GLOBAL_RULES.safeClassName.join(' '),
    '',
    '### Forbidden className (use props):',
    GLOBAL_RULES.forbiddenClassName.join(' '),
    '',
    '---',
    '',
  ];

  for (const component of components) {
    lines.push(`## ${component.name}`);
    lines.push('');

    const appearanceProp = findAppearanceProp(component.props);
    const appearanceProps = appearanceProp ? [appearanceProp] : [];
    const stateProps = findStateProps(component.props);

    lines.push('### ALLOWED');
    if (appearanceProps.length === 0 && stateProps.length === 0) {
      lines.push(
        `- Props not yet extracted — use Storybook docs for prop reference: ${component.docsUrl}`
      );
    }
    for (const prop of appearanceProps) {
      const ex = prop.options?.length
        ? `<${component.name} ${prop.name}="${prop.options[0]}" />`
        : prop.type === 'boolean'
          ? `<${component.name} ${prop.name} />`
          : `<${component.name} ${prop.name}="..." />`;
      lines.push(`- ${prop.name} prop for appearance: \`${ex}\``);
    }
    for (const prop of stateProps) {
      lines.push(`- ${prop.name} prop for state: \`<${component.name} ${prop.name} />\``);
    }
    lines.push(`- className for margin only: \`<${component.name} className="mt-4" />\``);
    lines.push(`- Wrapper div for layout: \`<div className="flex"><${component.name} /></div>\``);
    lines.push('');

    lines.push('### FORBIDDEN');
    for (const bullet of buildForbiddenBullets(component.name)) {
      lines.push(`- \`${bullet}\``);
    }
    lines.push('');

    const v1 = component.props.find((p) => p.name === 'variant')?.options?.[0] || '';
    const v2 = component.props.find((p) => p.name === 'variant')?.options?.[1] || '';

    lines.push('### COMPOSITION');
    lines.push('```tsx');
    lines.push('// Correct: props for appearance, wrapper for layout');
    lines.push('<div className="flex gap-2">');
    lines.push(
      v2
        ? `  <${component.name} variant="${v2}">Cancel</${component.name}>`
        : `  <${component.name}>Cancel</${component.name}>`
    );
    lines.push(
      v1
        ? `  <${component.name} variant="${v1}">Save</${component.name}>`
        : `  <${component.name}>Save</${component.name}>`
    );
    lines.push('</div>');
    lines.push('// Wrong: visual overrides via className');
    lines.push(`<${component.name} className="bg-brand-500 p-4 rounded-none">Submit</${component.name}>`);
    lines.push('```');
    lines.push('');

    if (component.variants.length > 0) {
      lines.push(`**Variants:** ${component.variants.join(' | ')}`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  fs.writeFileSync(path.join(outputDir, 'RULES.md'), lines.join('\n'), 'utf-8');
}
